# Copyright (c) 2025 Margins Technologies LLC.

name: ⚠️ Bug Report
description: Report unexpected or incorrect behavior, performance issues, or crashes.
labels:
  - bug
  - triage
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what happened.
      placeholder: Describe what happened
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Step-by-step instructions to consistently reproduce the issue.
      placeholder: Describe how to reproduce the issue with step-by-step instructions
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of the expected behavior.
      placeholder: Describe what should have happened
    validations:
      required: true
  - type: input
    attributes:
      label: App Version
      description: The Combine Editor version on which the issue occurred. The app version may be found in the App Data section of Combine Editor Settings.
      placeholder: ex. 1.0.0 (5)
    validations:
      required: true
  - type: input
    id: ios-ipados-version
    attributes:
      label: iOS or iPadOS Version
      description: The iOS or iPadOS version on which the issue occurred. The iOS or iPadOS version may be found in iOS or iPadOS Settings.
      placeholder: ex. iOS 18.5
    validations:
      required: true
  - type: input
    attributes:
      label: Device
      description: The device on which the issue occurred. The device model name may be found in iOS or iPadOS Settings.
      placeholder: ex. iPhone 16 Pro Max
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Additional information which may help.
      placeholder: Any additional information
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Other
      options:
        - label: >
            I understand that by submitting feedback, I hereby irrevocably assign all intellectual property
            rights to Margins Technologies LLC (the developer of Combine Editor) and that my feedback may be used
            without restriction, without compensation to me, and without attribution to me.
          required: true
