# Copyright (c) 2025 Margins Technologies LLC.

name: ✨ Feature Request
description: Request a new feature, an improvement to an existing feature, or another change.
labels:
  - enhancement
  - triage
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the new feature, improvement, or change.
      placeholder: Describe the new feature, improvement, or change
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: A clear and concise description of how the new feature, improvement, or change would benefit users.
      placeholder: Describe how the new feature, improvement, or change would benefit users
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Additional information which may help.
      placeholder: Any additional information
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Other
      options:
        - label: >
             By submitting any question, comment, suggestion, idea, feedback, or other information,
             I agree to assign to Margins Technologies LLC (the developer of Combine) all intellectual 
             property rights in such Submission. I agree that Margins Technologies LLC shall own this Submission 
             and be entitled to its unrestricted use and dissemination for any lawful purpose, commercial or 
             otherwise, without acknowledgment or compensation to me.
          required: true
