# Copyright (c) 2025 Margins Technologies LLC.

name: â“ General Support
description: Request general support for something other than a Bug Report or Feature Request.
labels:
  - question
  - triage
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the support request.
      placeholder: Describe the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Additional information which may help.
      placeholder: Any additional information
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Other
      options:
        - label: >
             By submitting any question, comment, suggestion, idea, feedback, or other information,
             I agree to assign to Margins Technologies LLC (the developer of Combine Editor) all intellectual 
             property rights in such Submission. I agree that Margins Technologies LLC shall own this Submission 
             and be entitled to its unrestricted use and dissemination for any lawful purpose, commercial or 
             otherwise, without acknowledgment or compensation to me.
          required: true
